# 小程式

數據分析練習

In [2]:
%pylab inline 
%matplotlib inline

import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

Populating the interactive namespace from numpy and matplotlib


### 1.算閏年 

In [8]:
def year():
    year = input("西元")
    year = int(year)
    if ((year%4==0 and year%100!=0) or (year%400==0)):
        print("{}是閏年".format(year))
    else:
        print("{}不是閏年".format(year))

In [10]:
year()

西元1986
1986不是閏年


### 2. 5*5 矩陣加法

In [14]:
def matrix_plus():
    m1 = np.random.randn(5,5)
    m2 = np.random.randn(5,5)
    print(m1+m2)

In [15]:
matrix_plus()

[[ 1.33469137 -0.28547655  1.09129828 -1.60828297 -0.56894031]
 [-1.81708473 -1.29310391 -0.00364264  0.85554768 -0.30845008]
 [-0.30628506  0.52591145  0.53152037  0.77717482  1.34234419]
 [ 2.46258783  0.0658998  -1.50274907 -2.81493308 -0.16137211]
 [-1.35965794 -0.7566572  -2.06820239  0.20257233  0.86094593]]


### 3.錄取分數表格

In [19]:
header = ["國文", "英文", "數甲", "數乙", "物理", "化學", "生物", "歷史", "地理", "公民"]

score =  [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]

dep_w = {
"土語系": [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
"財政系": [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
"金融系": [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
"國貿系": [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
"會計系": [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
"法律系": [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
"公行系": [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
"應數系": [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
"教育系": [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]
} 

In [37]:
d = []
f = []

for i in dep_w:
    f.append(i)
    d.append(dep_w[i])
    
df = pd.DataFrame(d, index = f, columns = header)

In [40]:
df["加權分數"] = (df[header]*score).sum(1)

In [41]:
df

國文   英文   數甲    數乙  物理  化學  生物  歷史  地理    公民     加權分數
土語系  2.0  2.0  0.0  1.00   0   0   0   1   1  0.00  589.200
財政系  1.0  1.5  0.0  1.50   0   0   0   0   0  0.00  350.350
金融系  1.0  1.5  0.0  2.00   0   0   0   0   0  0.00  398.600
國貿系  1.5  2.0  0.0  2.00   0   0   0   0   0  0.00  481.550
會計系  1.5  2.0  0.0  2.00   0   0   0   1   1  0.00  642.450
法律系  1.0  2.0  0.0  1.00   0   0   0   1   0  1.00  508.900
公行系  1.0  1.5  0.0  1.25   0   0   0   0   0  1.25  436.975
應數系  1.0  1.0  1.5  0.00   1   1   0   0   0  0.00  461.300
教育系  1.5  2.0  0.0  1.25   0   0   0   1   1  0.00  570.075